In [1]:
import numpy as np
a = np.array([10,20,30])
print(a)

[10 20 30]


In [17]:
b = np.linspace(1, 10, num = 2)
print(b)

[ 1. 10.]


In [23]:
c = np.arange(5)
print(c)

[0 1 2 3 4]


In [25]:
x = np.zeros(5)
print(x)
#similar can be done with ones

[0. 0. 0. 0. 0.]


In [35]:
#2D array with Numpy
x = np.array([[2,4,6], [1,3,5]])
print(x)

[[2 4 6]
 [1 3 5]]


In [37]:
#ndim attribute
#to know the number of rows of an array
a = np.array([1,2,3])
x = np.array([[2,4,6], [1,3,5]])

print(a.ndim)
print(x.ndim)

1
2


In [39]:
#shape attribute

x = np.array([[2,4,6], [1,3,5]])
print(x.shape) #2 rows 3 columns

(2, 3)


In [43]:
#size attribute

x = np.array([[2,4,6], [1,3,5]])
print(x.size)

6


In [63]:
#reshape method
x = np.array([[2,4,6], [1,3,5]])
d = x.reshape(3,2)
print(d)

[[2 4]
 [6 1]
 [3 5]]


In [67]:
#concatenate

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.concatenate([a,b])
print(c)

[1 2 3 4 5 6]


In [69]:
#hstack to join more than one array horizontally or Row wise
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


In [71]:
#vstack to join more than one array vertically or column wise

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]
